[build]
  publish = "/"
  command = "node build.js"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  GOOGLE_MAPS_API_KEY = ""
  SPREADSHEET_ID = "" 